export const ALL_CATEGORIES = [
  { label: "روايات", topic: "fiction" },
  { label: "أدب كلاسيكي", topic: "classics" },
  { label: "مغامرات", topic: "adventure" },
  { label: "غموض وجريمة", topic: "mystery" },
  { label: "تاريخ", topic: "history" },
  { label: "فلسفة", topic: "philosophy" },
  { label: "علم نفس", topic: "psychology" },
  { label: "شعر", topic: "poetry" },
  { label: "سير ذاتية", topic: "biography" },
  { label: "فنون", topic: "art" },
  { label: "خيال علمي", topic: "science fiction" },
  { label: "علوم سياسية", topic: "politics" },
  { label: "علوم اجتماعية", topic: "social sciences" },
  { label: "اقتصاد", topic: "economics" },
  { label: "جغرافيا", topic: "geography" },
];
